chess_stats/analyze_app/urls.py
from django.urls import path

from . import views

app_name = "report"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("reports/", views.ReportListView.as_view(), name="report-list"),
    path("create/", views.ReportCreateView.as_view(), name="report-create"),
    path("<int:id>/", views.ReportDetailView.as_view(), name="report-detail"),
    path(
        "<int:id>/visualized",
        views.VisualizedReportDetailView.as_view(),
        name="report-visualized",
    ),
    path("<int:id>/delete", views.ReportDeleteView.as_view(), name="report-delete"),
    # path("<int:id>/games", views, name="report-games"),
]

chess_stats/chess_stats/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("analyze_app.urls")),
]

chess_stats/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("analyze_app.urls")),
]

chess_stats/analyze_app/models.py
from collections.abc import Iterable
from django.db import models, transaction


class Color(models.TextChoices):
    WHITE = "white"
    BLACK = "black"


class Result(models.TextChoices):
    WHITE = Color.WHITE
    DRAW = "draw"
    BLACK = Color.BLACK


class Report(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    chess_com_username = models.CharField(max_length=100)
    lichess_username = models.CharField(max_length=100)
    time_class = models.CharField(max_length=20)
    games_num = models.IntegerField()
    analyzed_games = models.IntegerField(default=0, null=True)
    engine_depth = models.IntegerField(default=10)
    fail_reason = models.CharField(max_length=100, null=True, blank=True)
    professional = models.BooleanField(blank=True, null=True)

    def __str__(self):
        return self.chess_com_username + " " + self.lichess_username


class SingleGamePlayer(models.Model):
    evaluation = models.JSONField(help_text="Evaluation of the player per phase.")
    elo = models.IntegerField(help_text="ELO rating of the player.")
    avg_move_time = models.JSONField(
        help_text="Average move time of the player per phase."
    )


# Generated basing on chess-insight readme
class ChessGame(models.Model):
    report = models.ForeignKey(
        Report, on_delete=models.CASCADE, related_name="games", null=True
    )
    player = models.ForeignKey(
        SingleGamePlayer,
        on_delete=models.CASCADE,
        related_name="player",
        help_text="Player object.",
    )
    opponent = models.ForeignKey(
        SingleGamePlayer,
        on_delete=models.CASCADE,
        related_name="opponent",
        help_text="Opponent object.",
    )

    date = models.DateTimeField(help_text="Date and time of the game in UTC.")
    host = models.CharField(
        max_length=255, help_text="Server where the game was played."
    )
    opening = models.CharField(max_length=255, help_text="Opening name in ECO format.")
    opening_short = models.CharField(
        max_length=50, help_text="Short opening name in ECO format."
    )

    phases = models.JSONField(
        help_text="Phases in half moves in the format (opening, middle game, end game)."
    )

    player_color = models.CharField(
        max_length=10, help_text="Player color in the game.", choices=Color.choices
    )
    result = models.CharField(max_length=60, choices=Result.choices)
    end_reason = models.CharField(
        max_length=50, help_text="Reason of the game end. e.g., 'checkmate'"
    )
    time_class = models.CharField(max_length=50, help_text="Time class of the game.")
    time_control = models.CharField(
        max_length=50,
        help_text="Time control in the format 'time+increment' in seconds. e.g., '600+0' or '180+2'",
    )
    url = models.URLField(help_text="URL to the game.")
    username = models.CharField(max_length=50, help_text="Username of the player.")

    def save(self, *args, **kwargs):
        # Create savepoints before saving objects
        with transaction.atomic():
            if not self.player.pk:
                self.player.save()
            if not self.opponent.pk:
                self.opponent.save()
            super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.date} - {self.username} url: {self.url}"

chess_stats/analyze_app/forms.py
from django import forms

from .models import Report


class ReportForm(forms.ModelForm):
    time_class = forms.ChoiceField(
        choices=[("rapid", "rapid"), ("blitz", "blitz"), ("bullet", "bullet")],
        initial="blitz",
    )
    chess_com_username = forms.CharField(
        initial="Hikaru",
        max_length=40,
        required=False,
        help_text="leave blank if you don't want to analyze chess.com games",
    )
    lichess_username = forms.CharField(
        initial="DrNykterstein",
        max_length=40,
        required=False,
        help_text="leave blank if you don't want to analyze lichess.org games",
    )
    games_num = forms.IntegerField(
        initial=50,
        min_value=1,
        max_value=1000,
        help_text="number of games to analyze Must be divisible by number of hosts",
    )
    professional = forms.BooleanField(
        help_text="Wether or not You are professional player.",
        initial=False,
    )
    engine_depth = forms.IntegerField(initial=5)

    class Meta:
        model = Report
        fields = (
            "time_class",
            "chess_com_username",
            "lichess_username",
            "games_num",
            "professional",
            "engine_depth",
        )

chess_stats/analyze_app/views.py
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
from django.views.generic import CreateView, DetailView, ListView, TemplateView
from django_q.tasks import async_task
from easy_logs import get_logger

from . import forms, models, queries
from .tasks import get_games

LOGGER = get_logger(lvl="DEBUG")


class IndexView(TemplateView):
    template_name = "index.html"

    # def get_absolute_url(self):
    #     return reverse("report:report-detail", kwargs={"id": self.id})


class ReportCreateView(CreateView):
    model = models.Report
    form_class = forms.ReportForm
    template_name = "create_report.html"

    def post(self, request):
        form = forms.ReportForm(request.POST)
        report = models.Report(
            chess_com_username=form.data["chess_com_username"],
            lichess_username=form.data["lichess_username"],
            time_class=form.data["time_class"],
            games_num=int(form.data["games_num"]),
            engine_depth=int(form.data["engine_depth"]),
            professional=bool(form.data.get("professional", False)),
        )
        report.save()
        async_task(get_games, report)
        return redirect(f"/{report.pk}/visualized")  # TODO CHANGE THIS TO REVERSE

    def get_absolute_url(self):
        return reverse("report:report-list")


class ReportDeleteView(DetailView):
    def get_object(self):
        _id = self.kwargs.get("id")
        report = get_object_or_404(models.Report, id=_id)
        return report

    def post(self, request, *args, **kwargs):
        _id = self.kwargs.get("id")
        report = get_object_or_404(models.Report, id=_id)
        report.delete()
        return redirect("report:report-list")


class ReportListView(ListView):
    template_name = "reports.html"
    queryset = models.Report.objects.all()


class ReportDetailView(DetailView):
    template_name = "report_detail.html"

    def get_object(self):
        id = self.kwargs.get("id")
        print(id)
        report = get_object_or_404(models.Report, id=id)
        games = models.ChessGame.objects.filter(report=report)
        return games

    def get_absolute_url(self):
        return reverse("report:report-detail", kwargs={"id": self.id})


class VisualizedReportDetailView(DetailView):
    template_name = "visualized_wraper.html"

    def get_object(self):
        id = self.kwargs.get("id")
        report = get_object_or_404(models.Report, id=id)
        if not models.ChessGame.objects.filter(report=self.kwargs.get("id")).exists():
            return {
                "Xanalyzed_games": {
                    "total": report.analyzed_games,
                },
                "Xfail_reason": report.fail_reason,
            }
        queries_maker = queries.QueriesMaker(report, LOGGER)
        data = queries_maker.asdict()
        # conclusion_maker = ConclusionsMaker(data, LOGGER)
        # conclusions = conclusion_maker.asdict()
        # merge dicts
        # return {**data, **conclusions}
        from rich import inspect

        inspect(data)
        return data

    def get_absolute_url(self):
        return reverse("report:report-visualized", kwargs={"id": self.id})

chess_stats/analyze_app/templates/base.html
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
  <head>
    {% load static %}
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Analyse your chess performance</title>
    {% block extra_head %}{% endblock %}
    <link
      href="{% static 'fontawesomefree/css/fontawesome.css' %}"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="{% static 'fontawesomefree/css/brands.css' %}"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="{% static 'fontawesomefree/css/solid.css' %}"
      rel="stylesheet"
      type="text/css"
    />

    <link rel="stylesheet" href="../static/css/bootstrap.min.css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <script src="../static/js/bootstrap.min.js" defer></script>
  </head>
  <body class="d-flex flex-column h-100 w-100">
    {% include 'navbar.html' %}
    <main class="flex-shrink-0 m-0">{% block content %}{% endblock %}</main>
    <!-- <footer class="mt-auto rounded border" style="display: block">
      <div class="text-center p-3">
        © 2023 Copyright:
        <a
          class="text-white"
          href="https://github.com/michalskibinski109/chess-stats"
          >Michal Skibinski</a
        >
      </div>
    </footer> -->
  </body>
</html>

chess_stats/analyze_app/templates/create_report.html
{% extends 'base.html' %} {% load crispy_forms_tags %} {% block content %}

<div class="row align-items-center justify-content-center m-0">
  <div class="contianer col-9 m-4">
      <h1 class="display-3">Create new report</h1>
      <hr/>
      <form method="post" class="" novalidate>
        {% csrf_token %} {{ form|crispy }}
        <button type="submit" class="btn btn-success mt-4">
          create report
        </button>
        <button
          type="button"
          class="btn btn-danger mt-4 float-end"
          onclick="window.history.back()"
        >
          cancel
        </button>
      </form>
    </div>
  </div>
  {% endblock %}
</div>

chess_stats/analyze_app/templates/index.html
{% extends 'base.html' %}
{% block extra_head %}
  <link rel="stylesheet" href="../static/css/style.css" />
  <script src="../static/js/script.js" defer></script>
{% endblock extra_head %}
{% block content %}
  <div class="container-fluid">
    <main class="flex-shrink-0 m-0">
      <div class="background-div">
        <section>
          <div class="row justify-content-center m-0">
            <h1 class="display-1 text-center m-5">
              <span class="text-danger">W</span>elcome.
            </h1>
            <hr class="col-8" />
            <p class="m-1 m-lg-4 col-10 col-lg-0 fs-4">
              We are free and
              <span class="text-warning">open source</span> chess analysis app.
              We provide you with the best analysis of your games. Whenewer you
              feel stuck and you don't know what to do to improve your game, we
              are here to help you. We are using the latest
              <code>stockfish-16</code> engine, AI algorithms and data
              visualizations to help you understand your games. We are also
              providing you with the best
              <span class="text-warning">user interface</span> to make your
              journey as easy as possible.
            </p>
            <div class="row justify-content-center text-center">
              <div class="col-12 col-lg-2 hidden logo m-0 m-lg-4">
                <i class="icon fas fa-circle-check fa-10x p-3 text-primary"></i>
                <p class="display-6 text-center">Easy</p>
              </div>
              <div class="col-12 col-lg-2 hidden logo m-0 m-lg-4">
                <i class="icon fas fa-brain fa-10x p-3 text-primary"></i>
                <p class="display-6 text-center">Smart</p>
              </div>
              <div class="col-12 col-lg-2 hidden logo m-0 m-lg-4">
                <i class="icon fas fa-lock bg-primary fa-10x p-3 text-dark"></i>
                <p class="display-6 text-center">Secure</p>
              </div>
            </div>
          </div>
        </section>
        <section>
          <div class="row justify-content-center m-0 mt-5">
            <div class="col-12 col-lg-4 fs-5 m-0 m-lg-5 p-4">
              <h2 class="text-white">
                Use power of
                <a href="https://github.com/michalskibinski109/chess_insight"
                   class="text-warning">chess-insight</a>
              </h2>
              <p class="text-muted">
                Modern bash application for gathering chess data and analyzing
                chess games. Created by <b>Us</b>!
              </p>
              <ul class="text-muted">
                <li>Download games from lichess.org and chess.com</li>
                <li>
                  Analyze games using set of custom methods and stockfish-16
                  engine
                </li>
                <li>
                  Provides methods for exporting list of analyzed games to csv and
                  json
                </li>
              </ul>
            </div>
            <img src="../static/ssc.png"
                 class="col-11 col-lg-6 console m-0 my-3 m-lg-2"
                 alt="" />
          </div>
        </section>
        <section class="d-flex flex-column justify-content-center">
          <div class="row align-self-center">
            <div class="row justify-content-center">
              <div class="col-10 col-lg-3 rounded bg-primary fs-5 border m-1 m-lg-5 p-4">
                <h2 class="text-white">Track Your Chess Progress</h2>
                <p class="text-muted">
                  Unlock the power of data with our tool! Create detailed reports
                  of your chess games from
                  <code>chess.com</code>
                  and
                  <code>lichess.org</code>
                  for <b>free</b>. Discover your strengths and weaknesses, analyze
                  your strategies, and improve your game.
                </p>
              </div>
              <div class="col-10 col-lg-3 rounded bg-primary fs-5 border m-1 m-lg-5 p-4">
                <h2 class="text-white">Winning Insights</h2>
                <p class="text-muted">
                  Get the winning edge! Check your win ratio per opening, per time
                  control, and even per day of the week. Identify where you excel
                  and where you need to focus your efforts to become a better
                  chess player.
                </p>
              </div>
              <div class="col-10 col-lg-3 rounded bg-dark fs-5 border m-1 m-lg-5 p-4">
                <h2 class="text-white">Game Analysis Made Easy</h2>
                <p class="text-muted">
                  Experience the convenience of in-depth game analysis. Our tool
                  breaks down your games into phases and highlights your mistakes,
                  helping you learn and grow as a chess player.
                </p>
              </div>
            </div>
          </div>
          <div class="col-12 row align-items-center justify-content-center">
            <a class="btn btn-success col-10 col-lg-3 m-1 my-5 m-lg-5 p-2 fs-5"
               href="/create/">
              <i class="fa-solid fa-chess-king fa-2x"></i>
              <span class="fs-4">Get started</span>
            </a>
            <a class="btn btn-warning col-10 col-lg-3 m-1 mb-5 m-lg-5 p-2 fs-5"
               href="https://github.com/michalskibinski109/chess-stats">
              <i class="fa-brands fa-github fa-2x"></i>
              <span class="fs-4">github page</span>
            </a>
          </div>
        </section>
        <section class="d-flex flex-column">
          <div class="row m-2">
            <div class="col-0 col-lg-1"></div>
            <img src="../static/ss1.png"
                 class="rounded p-2 m-2 bg-primary col-11 col-lg-5"
                 alt="" />
            <div class="col-11 col-lg-4 text-center fs-5 p-5 text-muted hidden box">
              <h3 class="display-5">Powerfull visualizations</h3>
              Improve with our interactive visualizations. We provide you with the
              many different Unique charts and graphs to help you understand your
              games. You can filter games by sources and seed them combined.
            </div>
          </div>
          <div class="row m-2">
            <div class="col-0 col-lg-1"></div>
            <div class="col-11 col-lg-5 text-center fs-5 p-5 text-muted hidden box">
              <h3 class="display-5">All reports in one place</h3>
              You can create many different reports and save them in one place.
              Come back to them anytime you want. You can also share them with
              your friends. You can see list of all games with details in any
              report you want.
            </div>
            <img src="../static/ss2.png"
                 class="rounded p-2 m-2 bg-primary col-11 col-lg-5"
                 alt="" />
          </div>
          <div class="row m-2">
            <div class="col-0 col-lg-1"></div>
            <img src="../static/ss3.png"
                 class="rounded p-2 m-2 bg-primary col-11 col-lg-5"
                 alt="" />
            <div class="col-11 col-lg-4 text-center fs-5 p-5 text-muted hidden box">
              <h3 class="display-5">Highly customizable</h3>
              Play with our varius custom options to create the best report for
              your needs. You can choose engine depth
              <b>We are using latest <code>stockfish-16</code></b> number of
              games. Different sources such as <code>chess.com</code>,
              <code>lichess.org</code> and more to come.
            </div>
          </div>
        </section>
        <footer class="mt-auto rounded border" style="display: block">
          <div class="text-center p-3">
            © 2023 Copyright:
            <a class="text-white"
               href="https://github.com/michalskibinski109/chess-stats">Michal Skibinski</a>
          </div>
        </footer>
      </div>
    </main>
  </div>
{% endblock %}

chess_stats/analyze_app/templates/navbar.html
<!-- <nav class="navbar bg-primary sticky-top navbar-expand-lg rounded">
  <div class="container-fluid">
    <a class="navbar-brand text-light p-4 pb-0 pt-0" href="/">
      <i class="fa-solid fa-chess-king fa-2x"></i>
      <b class="fs-4">Chess Stats</b>
    </a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarCollapse"
      aria-controls="navbarCollapse"
      aria-expanded="false"
      aria-label="Toggle navigation"
      class="pr-0"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="d-flex">
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="col navbar navbar-nav mr-5 d-flex">
          <li class="nav-item">
            <a
              class="nav-link active text-start"
              aria-current="page"
              href="/reports"
              >All reports</a
            >
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/create"
              >Create report</a
            >
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/admin"
              >Admin</a
            >
          </li>
        </ul>
      </div>
    </div>
  </div>
</nav> -->

<nav class="navbar bg-primary sticky-top navbar-expand-lg rounded">
  <div class="container-fluid">
    <a class="navbar-brand text-light p-2 pb-0 pt-0" href="/">
      <i class="fa-solid fa-chess-king fa-2x"></i>
      <b class="fs-4">Chess Stats</b>
    </a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarNavAltMarkup"
      aria-controls="navbarNavAltMarkup"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a
            class="nav-link active text-start"
            aria-current="page"
            href="/reports"
            >All reports</a
          >
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/create"
            >Create report</a
          >
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/admin">Admin</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

chess_stats/analyze_app/templates/report_detail.html
{% extends 'base.html' %} {% block content %}

<div class="row align-items-center justify-content-center m-0">
  <div class="contianer col-12 col-lg-9 m-0 m-lg-4">
    <h1 class="display-3">Report details</h1>
    <hr />
    <div class="table-responsive">
      <table class="table">
        <thead>
          <tr>
            <th scope="col">game</th>
            <th scope="col">result</th>
            <th scope="col">host</th>
            <th scope="col">player color</th>
            <th scope="col">time class</th>
            <th scope="col">date</th>
            <th scope="col">elo</th>
            <th scope="col">opening</th>
            <th scope="col">Player elo</th>
          </tr>
        </thead>
        {% for game in object %}
        <tbody>
          <tr>
            <th scope="row"><a href="{{game.url}}">{{game.id}}</a></th>
            <td>{{game.get_result_display}}</td>
            <td>{{game.host}}</td>
            <td>{{game.get_player_color_display}}</td>
            <td>{{game.time_class}}</td>
            <td>{{game.date}}</td>
            <td>{{game.player.elo}}</td>
            <td>{{game.opening}}</td>
            <td>{{game.player.elo}}</td>

            {% endfor %}
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

{% endblock %}

chess_stats/analyze_app/templates/report_visualized.html
<div class="row">
  <div class="col-lg-8 p-0 p-lg-1 col-12">
    <div class="card card-chart">
      <div class="card-header">
        <div class="row">
          <div class="col-sm-6 text-left">
            {% load custom_filters %}
            <h3 class="card-title">
              {{ statistic_name | snake_to_user_readable }}
            </h3>
          </div>
          <div class="col-sm-6">
            <div class="btn-group" role="group">
              <input
                type="radio"
                class="btn-check"
                name="btnradio_{{statistic_name}}"
                id="{{statistic_name}}_total"
                autocomplete="off"
                checked
              />
              <label
                class="btn btn-outline-warning"
                for="{{statistic_name}}_total"
                >All</label
              >
              <input
                type="radio"
                class="btn-check"
                name="btnradio_{{statistic_name}}"
                id="{{statistic_name}}_chess_com"
                autocomplete="off"
              />
              <label
                class="btn btn-outline-warning"
                for="{{statistic_name}}_chess_com"
                >Chess.com</label
              >
              <input
                type="radio"
                class="btn-check"
                name="btnradio_{{statistic_name}}"
                id="{{statistic_name}}_lichess_org"
                autocomplete="off"
              />
              <label
                class="btn btn-outline-warning"
                for="{{statistic_name}}_lichess_org"
                >lichess</label
              >
            </div>
          </div>
        </div>
      </div>
      <div class="card-body col-12">
        <canvas id="{{statistic_name}}_chart"></canvas>
      </div>
    </div>
  </div>

  {% if object.Xprofessional.total %}
  <div
    class="col-12 col-lg-4 p-0 p-lg-1 mt-2 mb-2 m-lg-0"
    style="display: none"
  >
    {% else %}
    <div class="col-12 col-lg-4 p-0 p-lg-1 mt-2 mb-2 m-lg-0">
      {% endif %}
      <div class="card mb-2">
        <div class="card-header">
          <h2 class="card-title">About</h2>
        </div>
        <div class="card-body">
          {% with s=object|getattr:statistic_name %} {{s.about|safe}}
          {%endwith%}
        </div>
      </div>
    </div>
</div>

chess_stats/analyze_app/templates/visualized_wraper.html
{% extends 'base.html' %}
{% block extra_head %}
  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/chartjs-adapter-date-fns/dist/chartjs-adapter-date-fns.bundle.min.js"></script>
  <script src="../static/js/chartInterface.js" type="module" defer></script>
  <script src="../static/js/win_ratio_chart.js" type="module" defer></script>
  <script src="../static/js/openings_chart.js" type="module" defer></script>
  <script src="../static/js/win_per_opponent_rating_chart.js"
          type="module"
          defer></script>
  <script src="../static/js/end_reasons_chart.js" type="module" defer></script>
  <script src="../static/js/avg_time_per_move_chart.js" type="module" defer></script>
  <script src="../static/js/elo_over_time_chart.js" type="module" defer></script>
  <script src="../static/js/mistakes_per_phase_chart.js" type="module" defer></script>
{% endblock %}
{% block content %}
  <h4>{{ object|json_script:"data" }}</h4>
  <div class="row align-items-center justify-content-center m-0">
    <div class="contianer col-12 col-lg-9">
      <h1 class="display-4">
        Report for
        <span>
          <code> {{ object.Xusername.chess_com }} </code>
          <code> {{ object.Xusername.lichess_org }} </code>
        </span>
      </h1>
      <hr />
      {% if not object or object.Xanalyzed_games.total == 0 %}
        <div class="alert alert-info" role="alert">Gathering data...</div>
      {% elif object.Xanalyzed_games.total == -1 %}
        <div class="alert alert-danger" role="alert">Failed to create report: {{ object.Xfail_reason }}</div>
      {% elif object.Xanalyzed_games.total < object.Xgames_num.total %}
        <div class="alert alert-primary" role="alert">
          ❗We are still analizing games please wait.
          ( {{ object.Xanalyzed_games.total }} / {{ object.Xgames_num.total }} )❗
        </div>
      {% endif %}
      <div class="rounded mt-5 mb-5">
        {% for statistic_name in object.keys %}
          <p></p>
          {% if not statistic_name|first in 'X' %}
            <p></p>
            {% include 'report_visualized.html' %}
            <hr class="text-light mt-4 mb-4" />
          {% endif %}
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock %}